### ISSUE TITLE
Организационная встреча #1

### ISSUE THREAD

**Issue by katunilya** [sevryukov/TimetableMSTeamsIntegration#1]
## Подготовка к встрече 

- [x] @sevryukov назначте дату встречи
- [x] @hypnospinner подготовить схему архитектуры, предложенного решения (см. MS Teams) 
- [x] @hypnospinner подготовить вопросы для use-case'ов системы
- [x] @hypnospinner подготовить Contribution Guidelines

## Повестка встречи

- [ ] Обсуждение и систематизация use-case'ов системы
- [x] Обсуждение предложенного архитектурного решения
- [x] Обсуждение возможностей и устройства API Timetables
- [x] Формализация и орагнизация процессов работы (про репозиторий на GH, CG)
- [x] Распределить задачи и сроки в рамках изучения технических возможностей API, анализа области задачи и описания конечного решения

**Comment by katunilya** [comment]
## Use cases/User stories

1. Как будут сформированны команды в MS Teams?

Как я понимаю, для каждого набора (преподаватель * предмет * группа) должна быть сформированна команда в MS Teams. Как это будет произведено, откуда можно подтянуть данные? Т.е. как мы можем привязываться 

2. Как часто мы планируем занятия?

Будет ли это процесс постепенный и постоянный, на какой срок. Будут ли занятия автоматически спланированы на весь семестр или они будут планироваться по ходу семестра?

3. Мы разделяем удаление занятия и перенос? (может ли произойти просто отмена занятия без его переноса (предполагая, что он случится, но позже))

4. Что происходит при смене состава команды? В первую очередь преподавателя, я считаю что нужно отслеживать этот кейс.

5. В целом наша система должна как-то отслеживать состав групп или мы полагаем, что он всегда условно "правильный" и нам важно только знать команду?

6. Какие процессы могут быть встроены в даный пайплайн? Просто если есть очевидные требования на будущее, хочу их изначально учесть, чтобы при их непосредственной реализации не страдать и заранее построить достаточно гибкое решение

**Comment by katunilya** [comment]
> Данный текст может использоваться как основа

## Contribution Guidelines

Данное руководство формализует правила работы над проектом с использованием сервиса контроля версий GitHub и явялется частью рекомендованных сообществом GH действий по повышению качества кодовой базы (репозитория).

Общий шаблон работы представляет из себя следующий итеративный процесс:

1. Определяем задачи итерации.
1.1. Для каждой задачи создаем Issue и назначаем отвественного(-ых).
1.2. Если требуется, то до первых результатов, проводим предвариельное обсуждение в комментариях к Issue.

2. Каждая задача решается в отдельной ветке (название ветки `issues/<issue_number>` - это делается для упрощения процесса навигирования между ветками в браузере и упрощения названий веток).
2.1. В процессе решения задачи, каждый коммит начинается с префикса в виде названия ветки (также для навигации в бразуере).
2.2. Если какой-либо коммит явялется промежуточным и/или исправлением предыдущего не забудьте произвести rebase/squash.
2.3. Мы стремимся к тому, чтобы коммиты отражали лог внесенных изменений и не имели исправлений (если исправление, не явялется требуемым изменением).

3. По достижению некоторых положительных промежуточных результатов создается Pull Request и помечается как WIP (Work In Progress, в случае GH нужно пометить его как Draft при создании).
3.1. Дальнейшее обсуждение должно проводиться уже в комментариях к PR и по большей части касаться предложенной реализации.

4. По заверешнию работы над задачей делаем запрос на Code Review и ждем решения ревьюеров.

**Comment by sevryukov** [comment]
@hypnospinner м.б. Contribution Guidelines вынести в Wiki?

**Comment by katunilya** [comment]
@sevryukov этот документ входит в набор рекомендованных для создания "дружелюбных к сообществу" репозиториев (как файл с лицензией, Code of Conduct, шаблоны PR и Issues). По правилам он помещается в файл CONTRIBUTING.md в корневой папке репозитория (что я уже сделал)

**Comment by sevryukov** [comment]
@hypnospinner Да, я это понимаю и знаю, но меня смутил комментарий 
>Данный текст может использоваться как основа
И если CONTRIBUTING.md добавлялся как часть этой задачи, то почему не установлена ассоциация?

**Comment by sevryukov** [comment]
Fixed with commit 0ba76a5ac41eb8865baaff3071aeff74465b107c
