### ISSUE TITLE
Изучение MS Teams API

### ISSUE THREAD

**Issue by katunilya** [sevryukov/TimetableMSTeamsIntegration#2]
Требуется разобраться в возможностях MS Teams API, в частности уточнить следующие вопросы:

* как можно создавать и структурировать команды?

* как управлять составом команд через API?

* как планировать и изменять запланированные встречи?

* используемые протоколы безопасности

* Azure Active Directory для получения информации о пользователях

Для каждого вопроса требуется предоставить некоторое сжатое описание и полезные ссылки на документацию/гайды и т.д.

**Comment by mohorka** [comment]
**Создание и структурирование**
1)Создавать можно несколькими способами. 
Один из вариантов - создание команды из группы (группа - объект office 365) - судя по документации, лучше не использовать, так как этот вариант считается устаревшим и больше не поддерживается.
Остальные варианты сводятся к следующему: создание объекта типа Team с нужными нам параметрами и последующий запрос на добавление команды (в документации есть хороший пример создания). Причем есть возможность создания команды по специальным шаблонам - грубо говоря, это команда+ определенный набор приложений. Для нас подходит educationClass (студенты + преподаватель). Тут нужно учитывать, что шаблоны не поддерживают создание частных каналов. С другой стороны, educationClass по дефолту имеет неизменяемое значение видимости команды HiddenMembership, что дает нам, по сути, закрытую команду (список участников и материалы команды доступны только участникам и админу команды), следовательно, проблем возникнуть не должно.
Пример наиболее близкого к нашей ситуации случая описан [здесь под номером 7.](https://docs.microsoft.com/ru-ru/graph/api/team-post?view=graph-rest-beta&tabs=csharp)

2)Структурирование
[Получаем](https://docs.microsoft.com/ru-ru/graph/api/team-post?view=graph-rest-beta&tabs=csharp) имеющуюся команду по id.
Для [обновления](https://docs.microsoft.com/ru-ru/graph/api/team-update?view=graph-rest-beta&tabs=csharp) команды заводим новый объект Team и замещаем им исходный объект (его получаем по id).
Для [добавления нового участника](https://docs.microsoft.com/ru-ru/graph/api/team-post-members?view=graph-rest-beta&tabs=csharp) заводим новый объект типа AadUserConversationMember и через запрос по id команды добавляем участника.
[Обновление информации об участнике](https://docs.microsoft.com/ru-ru/graph/api/conversationmember-update?view=graph-rest-beta&tabs=csharp) происходит аналогично обновлению команды - создается новый объект-участник и им замещается исходный объект-участник (доступ к команде и участнику осуществляется по их id).

По автоматизации жизненного цикла команды (создание-настройка-использование-удаление) есть [туториал.](https://www.youtube.com/watch?v=0TVM5Wonpkg)

**Comment by katunilya** [comment]
@mohorka отличное начало!

Хочу уточнить несколько вопросов касательно инфраструктуры Microsoft. У нас есть ряд продуктов - Microsoft 365 (бывший MS Office 365), MS Graph, MS Teams и Azure Active Directory - как они соотносятся?

**Comment by mohorka** [comment]
@hypnospinner , вплане команд office 365 и teams соотносятся следующим образом - в teams есть объект команда (team), в office 365 - объект группа (group). Они эквивалентны друг другу в том смысле, что из имеющейся группы offic'a с помощью вызова специальной команды мы можем создать команду для teams. Но, как я писала выше, этот способ устаревший и Microsoft не рекомендует так делать.
Насчёт связи с остальными продуктами дополнительно гляну и отпишусь

**Comment by katunilya** [comment]
[База знаний](https://github.com/sevryukov/TimetableMSTeamsIntegration/wiki/MS-Teams-Api) по MS Graph API в достаточной мере сформирована
